In [1]:
!mamba install pandas numpy matplotlib seaborn scikit-learn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

mambajs 0.19.13

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas, seaborn, scikit-learn
Channels: emscripten-forge, conda-forge

Solving environment...
Solving took 3.131199999988079 seconds
  Name                          Version                       Build                         Channel
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
+ brotli-python                 1.2.0                         py313h33caa6c_0               emscripten-forge
+ certifi                       2026.5.20                     pyhd8ed1ab_0                  conda-forge
+ charset-normalizer            3.4.7                         pyhd8ed1ab_0                  conda-forge
+ idna                          3.17                          pyhcf101f3_0                  conda-forge
+ joblib                        1.5.3                         py313h1804a44_1               emscripten-forge
+ pandas                        3.0.2                         np22py313h9d9dc1e_0           emscripten-forge
+ patsy                         1.0.2                         py313h1804a44_1               emscripten-forge
+ pysocks                       1.7.1                         py313h1804a44_2               emscripten-forge
+ python-tzdata                 2026.2                        pyhd8ed1ab_0                  conda-forge
+ requests                      2.34.2                        pyhcf101f3_0                  conda-forge
+ scikit-learn                  1.8.0                         np22py313h2c67255_3           emscripten-forge
+ seaborn                       0.13.2                        hd8ed1ab_3                    conda-forge
+ seaborn-base                  0.13.2                        pyhd8ed1ab_3                  conda-forge
+ setuptools                    82.0.1                        pyh332efcf_0                  conda-forge
+ statsmodels                   0.14.6                        np22py313h3cf259a_1           emscripten-forge
+ threadpoolctl                 3.6.0                         pyhecae5ae_0                  conda-forge
+ urllib3                       2.2.2                         pyhd8ed1ab_0                  conda-forge
- pip                           25.3                          pyh145f28c_0                  conda-forge

In [2]:
df = pd.read_csv('DOHMH_HIV_AIDS_Annual_Report_20260519.csv')

/tmp/xpython_42/2800868487.py:1: DtypeWarning: Columns (0: HIV diagnoses, 1: HIV diagnosis rate, 2: AIDS diagnoses, 3: AIDS diagnosis rate, 4: PLWDHI prevalence, 5: Deaths, 6: HIV-related death rate, 7: Non-HIV-related death rate) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('DOHMH_HIV_AIDS_Annual_Report_20260519.csv')

In [3]:
#Data Cleaning: Removing all cammas on str and replacing the comma with a space/nothing. 
df = df.replace(',','', regex=True)

In [4]:
# Data Cleaning: Converting the colums with data type objet to a numeric data type. Some were converted to int and others to float based on the type of numeric data found in each column. 
colsInt = ['HIV diagnoses', 'AIDS diagnoses', 'Deaths'] 
df[colsInt] = df[colsInt].apply(pd.to_numeric, errors = 'coerce').fillna(0).astype(int)

colsFlo = ['HIV diagnosis rate', '% linked to care within 3 months', 'AIDS diagnosis rate', 'PLWDHI prevalence', '% viral suppression', 'Death rate', 'HIV-related death rate', 'Non-HIV-related death rate'] 
df[colsFlo] = df[colsFlo].apply(pd.to_numeric, errors = 'coerce').fillna(0).astype(float)

df.head()

,Year,Borough,UHF,Gender,Age,Race,HIV diagnoses,HIV diagnosis rate,Concurrent diagnoses,% linked to care within 3 months,AIDS diagnoses,AIDS diagnosis rate,PLWDHI prevalence,% viral suppression,Deaths,Death rate,HIV-related death rate,Non-HIV-related death rate
0,2011,All,All,All,All,All,3379,48.3,640.0,0.0,2366,33.8,1.1,0.0,2040,13.6,5.8,7.8
1,2011,All,All,Male,All,All,2595,79.1,480.0,0.0,1712,52.2,1.7,0.0,1423,13.4,5.7,7.7
2,2011,All,All,Female,All,All,733,21.1,153.0,0.0,622,17.6,0.6,0.0,605,14.0,6.0,8.0
3,2011,All,All,Transgender,All,All,51,99999.0,7.0,0.0,32,99999.0,99999.0,0.0,12,11.1,5.7,5.4
4,2011,All,All,Female,13 - 19,All,47,13.6,4.0,0.0,22,6.4,0.1,0.0,1,1.4,1.4,0.0

In [5]:
# Data Cleaning: Replacing all NaN with 0 for better accessing/reading of the data. 
df = df.fillna(0).replace('NaN', 0)

In [6]:
#Data Cleaning: Removing any row that contain the word All as this would be unusable for my analysis due to inconsistency on who data was entered as All. 
df = df[~df.astype(str).apply(lambda x: x.str.contains('All')).any(axis=1)]
df.head()

,Year,Borough,UHF,Gender,Age,Race,HIV diagnoses,HIV diagnosis rate,Concurrent diagnoses,% linked to care within 3 months,AIDS diagnoses,AIDS diagnosis rate,PLWDHI prevalence,% viral suppression,Deaths,Death rate,HIV-related death rate,Non-HIV-related death rate
6275,2017,Bronx,Crotona - Tremont,Men,18 - 29,Asian/Pacific Islander,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0.0,0.0
6276,2017,Bronx,Crotona - Tremont,Men,18 - 29,Black,9,154.9,0.0,0.0,4,68.9,2.9,0.0,0,0.0,0.0,0.0
6277,2017,Bronx,Crotona - Tremont,Men,18 - 29,Latinx/Hispanic,19,126.8,1.0,0.0,4,26.7,0.9,0.0,1,7.3,0.0,7.3
6278,2017,Bronx,Crotona - Tremont,Men,18 - 29,Other/Unknown,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0.0,0.0
6279,2017,Bronx,Crotona - Tremont,Men,18 - 29,White,0,0.0,0.0,0.0,0,0.0,3.0,0.0,0,0.0,0.0,0.0

In [7]:
#Data Statitis: Number of HIV diagnoses by year
HivSumByYear = df.groupby('Year')['HIV diagnoses'].sum()
display(HivSumByYear)

Year
2017    1794
2018    1668
2019    1533
2020    1258
2021    1368
2022    1403
Name: HIV diagnoses, dtype: int32

In [8]:
#Data Statistic: Number of AIDS diagnoses by year
AidsSumByYear = df.groupby('Year')['AIDS diagnoses'].sum()
display(AidsSumByYear)

Year
2017    1027
2018    1038
2019     941
2020     815
2021     907
2022     912
Name: AIDS diagnoses, dtype: int32

In [9]:
#Data Statistic: Number of HIV diagnoses by Race by Borough
HivSumByRace = df.groupby(['Borough', 'Race'])['HIV diagnoses'].sum()
display(HivSumByRace)

Borough        Race
Bronx          Asian/Pacific Islander      12
               Black                     1075
               Latinx/Hispanic           1142
               Other/Unknown                0
               White                       53
Brooklyn       Asian/Pacific Islander     104
               Black                     1617
               Latinx/Hispanic            685
               Other/Unknown               17
               White                      373
Manhattan      Asian/Pacific Islander      80
               Black                      689
               Latinx/Hispanic            685
               Other/Unknown                7
               White                      423
Queens         Asian/Pacific Islander     242
               Black                      542
               Latinx/Hispanic            923
               Other/Unknown               11
               White                      160
Staten Island  Asian/Pacific Islander       5
               Black                       86
               Latinx/Hispanic             49
               Other/Unknown                0
               White                       44
Name: HIV diagnoses, dtype: int32

In [10]:
#Data Statistic: Number of HIV diagnoses by Age by Borough
HivSumByAge = df.groupby(['Borough', 'Age'])['HIV diagnoses'].sum()
display(HivSumByAge)

Borough        Age
Bronx          18 - 29     857
               30 - 39     651
               40 - 49     325
               50 - 59     288
               60+         161
Brooklyn       18 - 29    1112
               30 - 39     811
               40 - 49     385
               50 - 59     314
               60+         174
Manhattan      18 - 29     683
               30 - 39     627
               40 - 49     259
               50 - 59     202
               60+         113
Queens         18 - 29     684
               30 - 39     588
               40 - 49     300
               50 - 59     209
               60+          97
Staten Island  18 - 29      70
               30 - 39      50
               40 - 49      26
               50 - 59      26
               60+          12
Name: HIV diagnoses, dtype: int32

In [11]:
#Data Statistic: Number of HIV Diagnoses by Borough, by Year, by Race: 
HivSumByAgeByRace = df.groupby(['Borough', 'Year', 'Race'])['HIV diagnoses'].sum()
pd.set_option('display.max_rows', None)
display(HivSumByAgeByRace)

Borough        Year  Race
Bronx          2017  Asian/Pacific Islander      1
                     Black                     201
                     Latinx/Hispanic           211
                     Other/Unknown               0
                     White                      13
               2018  Asian/Pacific Islander      2
                     Black                     198
                     Latinx/Hispanic           205
                     Other/Unknown               0
                     White                       9
               2019  Asian/Pacific Islander      2
                     Black                     221
                     Latinx/Hispanic           224
                     Other/Unknown               0
                     White                       6
               2020  Asian/Pacific Islander      2
                     Black                     137
                     Latinx/Hispanic           141
                     Other/Unknown               0
                     White                      11
               2021  Asian/Pacific Islander      4
                     Black                     151
                     Latinx/Hispanic           192
                     Other/Unknown               0
                     White                       6
               2022  Asian/Pacific Islander      1
                     Black                     167
                     Latinx/Hispanic           169
                     Other/Unknown               0
                     White                       8
Brooklyn       2017  Asian/Pacific Islander     23
                     Black                     315
                     Latinx/Hispanic           149
                     Other/Unknown               4
                     White                      93
               2018  Asian/Pacific Islander     24
                     Black                     303
                     Latinx/Hispanic           131
                     Other/Unknown               2
                     White                      67
               2019  Asian/Pacific Islander     12
                     Black                     257
                     Latinx/Hispanic           100
                     Other/Unknown               1
                     White                      64
               2020  Asian/Pacific Islander      8
                     Black                     253
                     Latinx/Hispanic            88
                     Other/Unknown               3
                     White                      53
               2021  Asian/Pacific Islander     25
                     Black                     242
                     Latinx/Hispanic            91
                     Other/Unknown               3
                     White                      45
               2022  Asian/Pacific Islander     12
                     Black                     247
                     Latinx/Hispanic           126
                     Other/Unknown               4
                     White                      51
Manhattan      2017  Asian/Pacific Islander     19
                     Black                     112
                     Latinx/Hispanic           132
                     Other/Unknown               1
                     White                     108
               2018  Asian/Pacific Islander     20
                     Black                     125
                     Latinx/Hispanic           125
                     Other/Unknown               2
                     White                      76
               2019  Asian/Pacific Islander     13
                     Black                     124
                     Latinx/Hispanic           121
                     Other/Unknown               1
                     White                      55
               2020  Asian/Pacific Islander      8
                     Black                     102
                     Latinx/Hispanic            94
                     Other/Unknown               1
                     White                      59
               2021  Asian/Pacific Islander     12
                     Black                     115
                     Latinx/Hispanic            93
                     Other/Unknown               2
                     White                      69
               2022  Asian/Pacific Islander      8
                     Black                     111
                     Latinx/Hispanic           120
                     Other/Unknown               0
                     White                      56
Queens         2017  Asian/Pacific Islander     61
                     Black                     108
                     Latinx/Hispanic           175
                     Other/Unknown               2
                     White                      31
               2018  Asian/Pacific Islander     47
                     Black                      96
                     Latinx/Hispanic           178
                     Other/Unknown               2
                     White                      28
               2019  Asian/Pacific Islander     34
                     Black                      98
                     Latinx/Hispanic           151
                     Other/Unknown               2
                     White                      17
               2020  Asian/Pacific Islander     35
                     Black                      77
                     Latinx/Hispanic           124
                     Other/Unknown               2
                     White                      38
               2021  Asian/Pacific Islander     35
                     Black                      81
                     Latinx/Hispanic           141
                     Other/Unknown               2
                     White                      21
               2022  Asian/Pacific Islander     30
                     Black                      82
                     Latinx/Hispanic           154
                     Other/Unknown               1
                     White                      25
Staten Island  2017  Asian/Pacific Islander      0
                     Black                      18
                     Latinx/Hispanic             8
                     Other/Unknown               0
                     White                       9
               2018  Asian/Pacific Islander      0
                     Black                      16
                     Latinx/Hispanic             6
                     Other/Unknown               0
                     White                       6
               2019  Asian/Pacific Islander      0
                     Black                      13
                     Latinx/Hispanic             8
                     Other/Unknown               0
                     White                       9
               2020  Asian/Pacific Islander      1
                     Black                      10
                     Latinx/Hispanic             7
                     Other/Unknown               0
                     White                       4
               2021  Asian/Pacific Islander      2
                     Black                      16
                     Latinx/Hispanic            10
                     Other/Unknown               0
                     White                      10
               2022  Asian/Pacific Islander      2
                     Black                      13
                     Latinx/Hispanic            10
                     Other/Unknown               0
                     White                       6
Name: HIV diagnoses, dtype: int32

In [12]:
#Saving the df with all changes so I can use this updated csv in Tablue for the visualization: 
df.to_csv('DOHMH_HIV_AIDS_Annual_Report_Clean.csv', index = False)